### ISSUE TITLE
VPCResourceController should release branch-eni resources for terminated Pods.

### ISSUE THREAD

**Issue by M00nF1sh** [aws/amazon-vpc-resource-controller-k8s#33] opened 2021-04-27 19:13 UTC
**What would you like to be enhanced**:
Pods created by Jobs will enter terminated state(Succeed/Failed), and the scheduler will treat resources used by terminated pods are released when making scheduling decision around resource limits.
For normal CNI workflow, kubelet will invoke DelNetwork for terminated pods, and our normal CNI will correctly reuse IP for new pods. 
However, for VPCResourceController, the branch-eni resource is still holding by terminated pods, and scheduler might schedule pod onto nodes where there are no branch-eni resource available. 

**Why is the change needed and what use case will it solve**:
We should change VPCResourceController to release the branch-eni resource for terminated pods as well.

**Comment by Shaiou** [comment] 2021-06-03 20:11
This would be really appreciated indeed. We've run into the issue many time where a pod would be scheduled but stuck in "creating" mode just because it was on a node with a terminated pod/job that did not release this eni.

**Comment by 0xkag** [comment] 2021-06-11 15:24
Enterprise customer here.  Also experiencing this issue.

**Comment by JacobHenner** [comment] 2021-08-23 14:17
This is causing a decent bit of operational pain, and confusion among our developers. Is there an ETA for when this might be addressed?

**Comment by abhipth** [comment] 2021-08-23 17:55
@JacobHenner Sorry for the inconvenience. This will be fixed in v1.1.0, which is planned for release in October.

**Comment by backjo** [comment] 2021-09-22 04:39
hi all - is this issue expected to occur on the Windows VPC Resource Controller that is currently used for enabling windows in https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html - the same type of issue seems to be manifesting for Windows CronJob pods that we've got running.

**Comment by abhipth** [comment] 2021-09-22 16:39
@backjo yes the issue is present in the Windows VPC Resource Controller as well. The old Windows controller is being deprecated and the Windows functionality will now be available in this controller from v1.1.0 release. The release will also have the fix for the issue you mentioned.

Sorry for the inconvenience, if you are on v1.21 then you can consider the [TTL](https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically) for cleaning up the Succeeded/Failed Jobs.

**Comment by backjo** [comment] 2021-09-22 16:51
Hey @abhipth  - thanks for the confirmation, this is super helpful. We're already using the TTL setting to help mitigate but wanted to confirm that this was a known IP leak on Windows.

**Comment by abhipth** [comment] 2021-11-10 03:04
Fix for the bug has been released for both Windows and Security Group for Pods and is available from EKS Platform versions mentioned in [v1.1.0 release](https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.1.0)

Note: The older Windows vpc-resource-controller (installed on data plane) is now deprecated and now the vpc-resource-controller is available on EKS Control Plane. See the [release](https://github.com/aws/amazon-vpc-resource-controller-k8s/releases/tag/v1.1.0) for more details.

**Closed by abhipth** 2021-11-10 03:04 UTC
Labels: bug
